export * from './envelope.js';
export * from './messages.js';
export * from './relay.js';
export * from './did.js';
export * from './agent.js';
export * from './payment.js';
export * from './escrow.js';
export * from './crypto.js';

// Ad Auction module (v1.0)
export {
  AdAuctionManager,
  getOrCreateAdAuctionManager,
  getAdAuctionManager,
  removeAdAuctionManager,
  getAuctionStats,
  getAllActiveBids,
  calculateVickreyPrice,
  calculateDecayedPrice,
  validateAdContent,
  formatBidAmount,
  getRecommendedBid,
  DEFAULT_AUCTION_CONFIG,
  SLOT_BASE_PRICES,
  type AdSlotType,
  type AdContent,
  type BidRequest,
  type Bid,
  type AuctionSlot,
  type BudgetAllocation,
  type AdBudget,
  type BidResult,
  type AuctionConfig
} from './ad-auction.js';

// Batch escrow operations
export {
  batchRelease,
  batchRefund,
  type BatchEscrowOptions
} from './escrow.js';

// Echo Survival mechanism (v1.4)
export {
  EchoSurvivalManager,
  getOrCreateSurvivalManager,
  getSurvivalManager,
  removeSurvivalManager,
  DEFAULT_SURVIVAL_CONFIG,
  formatSurvivalReport,
  shouldAcceptTask,
  type AgentHealth,
  type AgentEconomics,
  type SurvivalCheckResult,
  type HeartbeatRecord,
  type SurvivalConfig,
  type AgentHealthStatus,
  type SurvivalSnapshot,
  type TaskDecision,
  type SurvivalEventType,
  type SurvivalEventCallback,
  type SurvivalAction,
  type SurvivalActionType,
  type SurvivalActionPriority
} from './survival.js';

// Wallet management (v1.1)
export {
  generateWallet,
  loadOrCreateWallet,
  loadWallet,
  saveEncryptedWallet,
  getWalletAddress,
  walletExists,
  getWalletPath,
  AGORA_DIR,
  WALLET_FILE,
  type WalletData,
  type AgentWallet
} from './wallet-manager.js';

// Multi-chain wallet management (v1.2)
export {
  createMultiChainClient,
  createMultiChainWallet,
  loadOrCreateMultiChainWallet,
  refreshBalances,
  getTotalUSDCBalance,
  getChainWithHighestBalance,
  getCheapestChainForOperations,
  hasSufficientBalance,
  selectOptimalChain,
  MultiChainWalletManager,
  type MultiChainWallet,
  type ChainConfig
} from './wallet-manager.js';

// Cross-chain bridge (v1.2)
export {
  CrossChainBridge,
  createChainPublicClient,
  getUSDCBalance,
  getNativeBalance,
  getAllBalances,
  getBridgeQuote,
  findCheapestChain,
  estimateBridgeFee,
  SUPPORTED_CHAINS,
  USDC_ADDRESSES,
  LAYERZERO_ENDPOINTS,
  LAYERZERO_CHAIN_IDS,
  LAYERZERO_USDC_OFT,
  RPC_URLS,
  BridgeTransactionHistory,
  BridgeTransactionMonitor,
  BridgeError,
  defaultLogger,
  listenLayerZeroMessages,
  getBridgeHistory,
  type SupportedChain,
  type BridgeQuote,
  type ChainBalance,
  type BridgeResult,
  type BridgeTransaction,
  type BridgeTransactionFilter,
  type BridgeTransactionStatusDetails,
  type BridgeFeeEstimate,
  type BridgeErrorCode,
  type BridgeLogger,
  type BridgeEventType,
  type BridgeQuoteEvent,
  type BridgeTransactionEvent,
  type BridgeErrorEvent,
  type BridgeFeeEvent,
  type BridgeMonitoringEvent,
  type BridgeMonitoringStatusEvent,
  type BridgeMonitoringFailedEvent,
  type BridgeEventData,
  type LayerZeroMessageStatus
} from './bridge.js';

// Performance Optimization module (v1.0)
export {
  PerformanceMonitor,
  createPerformanceMonitor,
  benchmark,
  measureLatency,
  measureLatencyAsync,
  withLatencyTracking,
  withLatencyTrackingAsync,
  trackMemory,
  generateOptimizationReport,
  type PerformanceMetrics,
  type BenchmarkResult,
  type LatencyHistogram,
  type MemorySnapshot,
  type LeakDetectionResult,
  type SeverityLevel,
  type OptimizationRecommendation,
  type OptimizationReport,
  type AlertThresholds,
  type PerformanceMonitorConfig,
  type PerformanceAlert,
} from './performance.js';

// API Cache Layer (v1.0)
export {
  ApiCache,
  getGlobalCache,
  setGlobalCache,
  cachedFetch,
  withCache,
  type CacheEntry,
  type CacheStats,
  type CacheConfig,
  type CacheOptions,
  type CachedFetchOptions,
  type UseCachedFetchResult,
  type UseCachedFetch,
} from './cache.js';

// Agent Profile module (v1.1) - with frontend optimizations
export {
  ProfileManager,
  createProfileManager,
  calculateLevel,
  xpForNextLevel,
  levelProgress,
  getTierColor,
  getDefaultAchievements,
  // Frontend optimizations
  ProfileCache,
  getProfileCache,
  batchGetProfiles,
  checkProfileCompleteness,
  saveProfileToLocalStorage,
  loadProfileFromLocalStorage,
  clearProfileFromLocalStorage,
  createOptimisticProfileUpdate,
  uploadAvatar,
  type AgentProfile,
  type AchievementTier,
  type Achievement,
  type ProfileStats,
  type UpdateProfileRequest,
  type ReputationHistoryEntry,
  type ProfileCompleteness,
  type AvatarUploadResult,
  type OptimisticUpdate,
} from './profile.js';

// Agent Profile React Hooks (v1.0) - frontend integration
export {
  // Hooks
  useProfile,
  useMyProfile,
  useUpdateProfile,
  useProfileStats,
  useAchievements,
  useReputationHistory,
  useSearchProfiles,
  useLeaderboard,
  useProfileCompleteness,
  useUploadAvatar,
  useLevelProgress,
  useBatchProfiles,
  useProfileCache,
  // Initialization
  initializeProfileManager,
  setGlobalAuthToken,
  getGlobalAuthToken,
  getGlobalManager,
  // Types
  type ProfileContextValue,
  type ProfileProviderProps,
  type UseProfileOptions,
  type UseProfileResult,
  type UseMyProfileResult,
  type UseUpdateProfileResult,
  type UseProfileStatsResult,
  type UseAchievementsResult,
  type UseReputationHistoryResult,
  type UseSearchProfilesOptions,
  type UseSearchProfilesResult,
  type LeaderboardCategory,
  type UseLeaderboardOptions,
  type UseLeaderboardResult,
  type UseProfileCompletenessResult,
  type UseUploadAvatarResult,
  type UseLevelProgressResult,
  type UseBatchProfilesResult,
  type UseProfileCacheResult,
} from './profile-hooks.js';

// Reputation Oracle module (v1.0)
export {
  ReputationOracle,
  getOrCreateReputationOracle,
  getReputationOracle,
  resetReputationOracle,
  createEmptyReputation,
  addSignal,
  addTaskRating,
  addEndorsement,
  addDispute,
  updatePaymentReliability,
  calculateReputation,
  calculateReputationBreakdown,
  recalculateReputation,
  calculateDecay,
  calculateSignalValue,
  calculatePaymentReliability,
  calculateEndorsementValue,
  getReputationTier,
  getReputationTierColor,
  formatReputation,
  generateReputationReport,
  DEFAULT_REPUTATION_CONFIG,
  type ReputationTier,
  type ReputationSignalType,
  type ReputationSignal,
  type Endorsement,
  type TaskRating,
  type PaymentReliability,
  type DisputeRecord,
  type ReputationBreakdown,
  type AgentReputation,
  type ReputationConfig,
  type ReputationCalcOptions,
  type ReputationUpdateResult,
} from './reputation.js';

// End-to-End Encryption (E2EE) module (v1.0)
export {
  E2EESessionManager,
  getOrCreateE2EEManager,
  getE2EEManager,
  resetE2EEManager,
  createEncryptedEnvelope,
  decryptEnvelope,
  DEFAULT_E2EE_CONFIG,
  type E2EESession,
  type EncryptedPayload,
  type E2EEConfig,
  type E2EEEvent,
  type E2EEEventType,
  type E2EEEventHandler,
} from './e2ee.js';

// Analytics module (v1.0) - Comprehensive analytics infrastructure
export {
  AnalyticsManager,
  EventTracker,
  MetricsCollector,
  getOrCreateAnalyticsManager,
  getAnalyticsManager,
  removeAnalyticsManager,
  createPerformanceMonitor as createAnalyticsPerformanceMonitor,
  type Severity as EventSeverity,
  type AlertSeverity as EventCategory,
  type MetricType,
  type PrivacyLevel,
  type AggregatedMetrics,
  type AnalyticsEvent,
  type MetricValue as Metric,
  type TimeSeriesData,
  type Alert as AnalyticsAlert,
  type ExportOptions,
  type PrivacyContext,
  type AgentPerformance,
  type UserEngagement,
  type RevenueMetrics,
  type SystemHealth,
  type DashboardSnapshot,
  type AnalyticsConfig,
  type MetricValue,
  type Session,
} from './analytics.js';

// Analytics Charts module (v1.0) - Chart data visualization helpers
export {
  toLineChartData,
  toBarChartData,
  toPieChartData,
  toAreaChartData,
  calculateWoW,
  calculateMoM,
  calculateYoY,
  formatPercentageChange,
  toKpiCardData,
  toSparklineData,
  toHeatmapData,
  metricsToTimeSeries,
  groupTimeSeriesByLabel,
  normalizeTimeSeries,
  mergeTimeSeries,
  calculateMovingAverage,
  DEFAULT_COLOR_PALETTE,
  type ChartDataPoint,
  type LineChartSeries,
  type LineChartData,
  type BarChartData,
  type PieChartData,
  type AreaChartData,
  type KpiMetric,
  type KpiCardData,
  type SparklineData,
  type HeatmapCell,
  type HeatmapData,
  type ChartFormatterOptions,
  type KpiCardOptions,
  type PercentageChangeOptions,
  type AggregatedDataPoint,
  type CategoryDataPoint,
  type GenericEvent,
} from './analytics-charts.js';

// Portfolio module (v1.0) - Agent storefront and portfolio management
export {
  calculateAgentScore,
  formatPriceRange,
  getStarRating,
  formatETA,
  type AgentPortfolio,
  type CaseStudy,
  type Testimonial,
  type PreviewRequest,
  type PreviewResponse,
  type ConsultantTask,
  type DecomposedTask,
  type SubTask,
  type AgentCandidate,
  type ConsultantRecommendation,
  type ConsultantExecution,
  type PurchaseOrder,
  type AgentResult,
  type AgentSearchQuery,
  type AgentSearchResult,
} from './portfolio.js';
