name: Feature request
description: Propose an improvement
title: "feat: "
labels: [feature]
body:
  - type: textarea
    id: idea
    attributes:
      label: The idea
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why it matters
